# Generated by Django 5.1.3 on 2024-11-23 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(default=datetime.datetime(2024, 11, 23, 19, 59, 19, 214507, tzinfo=datetime.timezone.utc))),
                ('check_out', models.DateField(default=datetime.datetime(2024, 11, 23, 19, 59, 19, 214524, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('P', 'Pending'), ('X', 'Cancelled')], default=None, max_length=10)),
            ],
        ),
    ]
