# Generated by Django 5.1.3 on 2024-11-23 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('method', models.CharField(choices=[('Credit', 'Credit'), ('Card', 'Card'), ('Cash', 'Cash'), ('Online', 'Online')], max_length=10)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
