# Generated by Django 5.1.3 on 2024-11-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot', '0002_alter_hotel_rating'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hotel_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_id', to='hot.hotel'),
            preserve_default=False,
        ),
    ]
