# Generated by Django 5.1.3 on 2024-11-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot', '0002_alter_hotel_rating'),
        ('room', '0002_room_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hot.hotel'),
        ),
    ]
