# Generated by Django 5.1.3 on 2024-11-24 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
        ('reservation', '0003_alter_reservation_status'),
        ('room', '0002_room_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='guest_id', to='guest.guest'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='room_id', to='room.room'),
        ),
    ]
