# Generated by Django 5.1.3 on 2024-11-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_reservation_id'),
        ('reservation', '0004_reservation_guest_id_reservation_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reservation_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_id', to='reservation.reservation'),
        ),
    ]
