# Generated by Django 5.1.3 on 2024-12-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hot', '0002_alter_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='facilities',
            field=models.TextField(),
        ),
    ]
